name = "Noteworthy-Hugo-Theme"
license = "MIT"
licenselink = "https://github.com/kimcc/hugo-theme-noteworthy/blob/master/LICENSE.md"
description = "An RStudio-Blogdown-Hugo site for MCC's blog"
homepage = "https://mcc1.netlify.com/"
tags = ["blog", "minimalist", "minimal", "clean", "simple", "responsive", "light"]
features = ["blog", "responsive", "social media"]
min_version = "0.55.2"

[author]
    name = "mcc"
    homepage = "https://mcc1.netlify.com/"
