baseURL = "https://mcc1.netlify.com/"
languageCode = "en-us"
title = "Matthew Curcio"
theme = "hugo-theme-noteworthy"
enableRobotsTXT = true
paginate = 4 # Set the number of posts to show before overflowing to the next page.
summaryLength = 10 # Configure how long the post summary should be on the homepage.

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Add your Google Analytics identifier: UA-XXXXXXXX-X
googleAnalytics = "UA-161598868-1" 

# Add your Disqus shortname here.
disqusShortname = ""    

[taxonomies]
tag = "tags"

[author]
name = "mcc"

# Set to false to disallow raw HTML in markdown files
[markup.goldmark.renderer]
    unsafe = true

[params]
	math = true
	# Blog description at the top of the homepage. Supports markdown.
	description = "Scientist, Teacher & Student of R & Python programmer, focusing on Machine Learning, Biochemistry, Biotechnology with my sights set on Data Science.  
	---"

	# Add links to your accounts. Remove the ones you don't want to include.
	# Main
	email = "mailto:matt.curcio.ri@gmail.com"
    twitter = "https://www.twitter.com/oaxacamatt1"
	youtube = "https://www.youtube.com/channel/UCkIkc77YacDWe1ieUFpMsFQ"
	linkedin = "https://www.linkedin.com/in/mattcurcio/"
    github = "https://www.github.com/mccurcio"
	stackoverflow = "https://stackoverflow.com/users/851043/oaxacamatt"

# Menu links along the sidebar navigation.
[[menu.main]]
	identifier = "about"
	name = "About"
	url = "/about/"
	weight = 1 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

[[menu.main]]
	identifier = "tags"
	name = "Tags"
	url = "/tags/"
	weight = 2

[[menu.main]]
	name = "Archives"
	identifier = "archives"
	url = "/archives/"
	weight = 3

# Privacy configurations: https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
